no change     /shared/centos7/anaconda3/3.7/condabin/conda
no change     /shared/centos7/anaconda3/3.7/bin/conda
no change     /shared/centos7/anaconda3/3.7/bin/conda-env
no change     /shared/centos7/anaconda3/3.7/bin/activate
no change     /shared/centos7/anaconda3/3.7/bin/deactivate
no change     /shared/centos7/anaconda3/3.7/etc/profile.d/conda.sh
no change     /shared/centos7/anaconda3/3.7/etc/fish/conf.d/conda.fish
no change     /shared/centos7/anaconda3/3.7/shell/condabin/Conda.psm1
no change     /shared/centos7/anaconda3/3.7/shell/condabin/conda-hook.ps1
no change     /shared/centos7/anaconda3/3.7/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /shared/centos7/anaconda3/3.7/etc/profile.d/conda.csh
no change     /home/agarwal.rishi/.bashrc
No action taken.
Traceback (most recent call last):
  File "Routine_Square_Code.py", line 588, in <module>
    main(sys.argv[1], int(sys.argv[2]))
ValueError: invalid literal for int() with base 10: '[27.436407359332986,-7.57841301205225],'
